import { Navbar } from '../components/Navbar'
import Head from 'next/head'
import styles from './MainLayout.module.css'
import { FC, ReactNode } from 'react'

type childNode = {
  children: ReactNode
}

export const MainLayout: FC<childNode> = ({ children }) => {
  return (
    <div className={styles.container}>

      {/* Head es la información que se incrusta al header de la página */}
      <Head>
        <title>Home - Adrián</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className={styles.main}>
        { children }
      </main>
    </div>
  )
}
